api_version = "2026-01"

[[extensions]]

name = "PAY.co.mz Offsite Payments"
handle = "payco-mz-offsite"
type = "payments_extension"

merchant_label = "PAY.co.mz"
buyer_label = "PAY.co.mz"

payment_session_url = "https://payco-shopify-production.onrender.com/payments/shopify/session"

refund_session_url = "https://payco-shopify-production.onrender.com/payments/shopify/refund"

supported_countries = ["MZ"]

supported_payment_methods = ["mpesa", "visa"]

supports_3ds = true
supports_installments = false
supports_deferred_payments = false
test_mode_available = false

[[extensions.targeting]]
target = "payments.offsite.render"
